# Generated by Django 5.1.6 on 2025-02-27 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_created_at_department_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='employee_count',
            field=models.IntegerField(default=0),
        ),
    ]
